# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import key_service_pb2 as key__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in key_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantumKeyServiceStub:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireKeys = channel.unary_unary(
                '/qko.v1.QuantumKeyService/AcquireKeys',
                request_serializer=key__service__pb2.AcquireKeyRequest.SerializeToString,
                response_deserializer=key__service__pb2.AcquireKeyResponse.FromString,
                _registered_method=True)
        self.GetPoolStatus = channel.unary_unary(
                '/qko.v1.QuantumKeyService/GetPoolStatus',
                request_serializer=key__service__pb2.PoolStatusRequest.SerializeToString,
                response_deserializer=key__service__pb2.PoolStatusResponse.FromString,
                _registered_method=True)
        self.RegisterRouter = channel.unary_unary(
                '/qko.v1.QuantumKeyService/RegisterRouter',
                request_serializer=key__service__pb2.RegisterRouterRequest.SerializeToString,
                response_deserializer=key__service__pb2.RegisterRouterResponse.FromString,
                _registered_method=True)
        self.DeregisterRouter = channel.unary_unary(
                '/qko.v1.QuantumKeyService/DeregisterRouter',
                request_serializer=key__service__pb2.RegisterRouterRequest.SerializeToString,
                response_deserializer=key__service__pb2.RegisterRouterResponse.FromString,
                _registered_method=True)
        self.SetRouterDemand = channel.unary_unary(
                '/qko.v1.QuantumKeyService/SetRouterDemand',
                request_serializer=key__service__pb2.SetDemandRequest.SerializeToString,
                response_deserializer=key__service__pb2.SetDemandResponse.FromString,
                _registered_method=True)
        self.StreamKeys = channel.unary_stream(
                '/qko.v1.QuantumKeyService/StreamKeys',
                request_serializer=key__service__pb2.AcquireKeyRequest.SerializeToString,
                response_deserializer=key__service__pb2.KeyMaterial.FromString,
                _registered_method=True)


class QuantumKeyServiceServicer:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def AcquireKeys(self, request, context):
        """Core key acquisition (called by Rust transport layer)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoolStatus(self, request, context):
        """Pool introspection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterRouter(self, request, context):
        """Router lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterRouter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRouterDemand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamKeys(self, request, context):
        """Streaming key feed (Rust transport subscribes for continuous delivery)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantumKeyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireKeys,
                    request_deserializer=key__service__pb2.AcquireKeyRequest.FromString,
                    response_serializer=key__service__pb2.AcquireKeyResponse.SerializeToString,
            ),
            'GetPoolStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolStatus,
                    request_deserializer=key__service__pb2.PoolStatusRequest.FromString,
                    response_serializer=key__service__pb2.PoolStatusResponse.SerializeToString,
            ),
            'RegisterRouter': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRouter,
                    request_deserializer=key__service__pb2.RegisterRouterRequest.FromString,
                    response_serializer=key__service__pb2.RegisterRouterResponse.SerializeToString,
            ),
            'DeregisterRouter': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterRouter,
                    request_deserializer=key__service__pb2.RegisterRouterRequest.FromString,
                    response_serializer=key__service__pb2.RegisterRouterResponse.SerializeToString,
            ),
            'SetRouterDemand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRouterDemand,
                    request_deserializer=key__service__pb2.SetDemandRequest.FromString,
                    response_serializer=key__service__pb2.SetDemandResponse.SerializeToString,
            ),
            'StreamKeys': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamKeys,
                    request_deserializer=key__service__pb2.AcquireKeyRequest.FromString,
                    response_serializer=key__service__pb2.KeyMaterial.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qko.v1.QuantumKeyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qko.v1.QuantumKeyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantumKeyService:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def AcquireKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qko.v1.QuantumKeyService/AcquireKeys',
            key__service__pb2.AcquireKeyRequest.SerializeToString,
            key__service__pb2.AcquireKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoolStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qko.v1.QuantumKeyService/GetPoolStatus',
            key__service__pb2.PoolStatusRequest.SerializeToString,
            key__service__pb2.PoolStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterRouter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qko.v1.QuantumKeyService/RegisterRouter',
            key__service__pb2.RegisterRouterRequest.SerializeToString,
            key__service__pb2.RegisterRouterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterRouter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qko.v1.QuantumKeyService/DeregisterRouter',
            key__service__pb2.RegisterRouterRequest.SerializeToString,
            key__service__pb2.RegisterRouterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRouterDemand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qko.v1.QuantumKeyService/SetRouterDemand',
            key__service__pb2.SetDemandRequest.SerializeToString,
            key__service__pb2.SetDemandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/qko.v1.QuantumKeyService/StreamKeys',
            key__service__pb2.AcquireKeyRequest.SerializeToString,
            key__service__pb2.KeyMaterial.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
