//! ML-DSA (Dilithium) integration.
//!
//! Wraps the `crystals-dilithium` crate from
//! https://github.com/Quantum-Blockchains/dilithium behind a stable local
//! adapter trait, `DilithiumScheme`, so the rest of the codebase never
//! touches the upstream crate's types directly.
//!
//! Used for IKEv2 packet *signing* (non-repudiation), NOT for key
//! generation. Long-term identity key material is expected to be
//! provisioned externally (HSM / sealed storage / orchestrator) and loaded
//! here via `from_provisioned_bytes`, not generated by this node.

use crate::error::NodeError;
use zeroize::Zeroize;

use crystals_dilithium::ml_dsa_65;
use crystals_dilithium::RandomMode;

/// Security parameter sets exposed by ML-DSA.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DilithiumLevel {
    MlDsa44,
    MlDsa65,
    MlDsa87,
}

/// Opaque signing key material. Zeroized on drop.
///
/// NOTE: `crystals_dilithium::ml_dsa_65::Keypair` carries both the secret
/// and public key together, and the crate's loading API
/// (`Keypair::from_bytes` / `Keypair::generate(seed)`) does not expose a
/// "load secret key only" constructor in the documented API. So in
/// practice the "provisioned bytes" you load here should be a serialized
/// Keypair (secret + public), exactly as produced by whatever provisioning
/// step generates it on the Key Management side — this node only loads
/// and uses it, never generates it.
pub struct SigningKey {
    level: DilithiumLevel,
    bytes: Vec<u8>,
}

impl Drop for SigningKey {
    fn drop(&mut self) {
        self.bytes.zeroize();
    }
}

impl SigningKey {
    pub fn from_provisioned_bytes(level: DilithiumLevel, bytes: Vec<u8>) -> Self {
        Self { level, bytes }
    }
}

#[derive(Debug, Clone)]
pub struct VerifyingKey {
    pub level: DilithiumLevel,
    pub bytes: Vec<u8>,
}

#[derive(Debug, Clone)]
pub struct Signature {
    pub bytes: Vec<u8>,
}

pub trait DilithiumScheme {
    fn sign(&self, sk: &SigningKey, message: &[u8]) -> Result<Signature, NodeError>;
    fn verify(&self, vk: &VerifyingKey, message: &[u8], sig: &Signature) -> Result<bool, NodeError>;
}

/// Concrete adapter over crystals-dilithium's ml_dsa_65 pure-mode API.
///
/// Only ML-DSA-65 is wired up below. If you need ml_dsa_44 / ml_dsa_87 too,
/// mirror this match-and-call pattern for those modules — the crate
/// exposes the identical method set (`Keypair`, `sign`, `verify`,
/// `from_bytes`) per security level, just under a different module path,
/// so there's no shared trait object across levels to dispatch through.
pub struct QbDilithium;

impl DilithiumScheme for QbDilithium {
    fn sign(&self, sk: &SigningKey, message: &[u8]) -> Result<Signature, NodeError> {
        match sk.level {
            DilithiumLevel::MlDsa65 => {
                let keypair = ml_dsa_65::Keypair::from_bytes(&sk.bytes)
                    .map_err(|e| NodeError::Pqc(format!("ML-DSA-65 keypair load failed: {e:?}")))?;

                let sig = keypair
                    .sign(message, None, RandomMode::Hedged)
                    .ok_or_else(|| NodeError::Pqc("ML-DSA-65 signing returned None".into()))?;

                Ok(Signature {
                    bytes: sig.to_vec(),
                })
            }
            other => Err(NodeError::Pqc(format!(
                "{other:?} not wired up yet - only MlDsa65 is implemented; see comment above QbDilithium"
            ))),
        }
    }

    fn verify(&self, vk: &VerifyingKey, message: &[u8], sig: &Signature) -> Result<bool, NodeError> {
        match vk.level {
            DilithiumLevel::MlDsa65 => {
                let public_key = ml_dsa_65::PublicKey::from_bytes(&vk.bytes)
                    .map_err(|e| NodeError::Pqc(format!("ML-DSA-65 public key load failed: {e:?}")))?;

                let signature: ml_dsa_65::Signature = sig
                    .bytes
                    .as_slice()
                    .try_into()
                    .map_err(|_| {
                        NodeError::Pqc(format!(
                            "ML-DSA-65 signature has wrong length: expected fixed-size array, got {} bytes",
                            sig.bytes.len()
                        ))
                    })?;

                Ok(public_key.verify(message, &signature, None))
            }
            other => Err(NodeError::Pqc(format!(
                "{other:?} not wired up yet - only MlDsa65 is implemented; see comment above QbDilithium"
            ))),
        }
    }
}

/// Convenience helper used by the IKEv2 non-repudiation layer.
pub struct DilithiumSigner<S: DilithiumScheme> {
    scheme: S,
}

impl<S: DilithiumScheme> DilithiumSigner<S> {
    pub fn new(scheme: S) -> Self {
        Self { scheme }
    }

    pub fn sign_packet(&self, sk: &SigningKey, packet_bytes: &[u8]) -> Result<Signature, NodeError> {
        self.scheme.sign(sk, packet_bytes)
    }

    pub fn verify_packet(
        &self,
        vk: &VerifyingKey,
        packet_bytes: &[u8],
        sig: &Signature,
    ) -> Result<bool, NodeError> {
        self.scheme.verify(vk, packet_bytes, sig)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_sign_verify() {
        let seed = [7u8; 32];
        let keypair = ml_dsa_65::Keypair::generate(Some(&seed)).expect("keygen failed");

        let sk = SigningKey::from_provisioned_bytes(DilithiumLevel::MlDsa65, keypair.to_bytes());
        // In real use the verifying key bytes come from the peer's public
        // key export, not derived locally like this - this test just
        // proves the adapter's sign/verify round-trips correctly.
        let vk = VerifyingKey {
            level: DilithiumLevel::MlDsa65,
            bytes: keypair.public.to_bytes(),
        };

        let scheme = QbDilithium;
        let msg = b"non-repudiation test packet";
        let sig = scheme.sign(&sk, msg).expect("sign failed");
        assert!(scheme.verify(&vk, msg, &sig).expect("verify failed"));
    }
}
